#   \zadachi-4t\_quarto.yml
#
project:
  type: website
  output-dir: docs


website:
  title: "zadachi posts github"
#     navbar:  	# zakommentarim   - dejstvuet    na vse dokumetru qmd
#       right:	# zakommentarim 
      # - about.qmd
#          - icon: github		# zakommentarim 
#            href: https://github.com/	# zakommentarim 
      # - icon: twitter
      #   href: https://twitter.com
      
   

#listing:
#  contents: "posts"

# mainfont:  "Helvetica New"
# monofont:  Consolas 
# sansfont:  Calibri
#   Если 3 строки выше не закомментарить, то текст на вебстранице идет шрифтом times
#   и она ( вебстраница) читается хуже
# "Times New Roman"     "Helvetica New" 
# Segoe UI Variable, "Andale Mono",  Roboto 
#
# Microsoft Sans Serif, Arial, and Verdana , Calibri are common choices that include Cyrillic characters
# Google fonts - Noto Sans , Open Sans 

   
format:
  html:
    theme:
    #   - cosmo
       - brand
    #theme:
    #  dark: solar
    #  light: cosmo
    css: styles.css
    
  


#  	https://quarto.org/docs/websites/website-navigation.html#top-navigation
#	https://quarto.org/docs/authoring/title-blocks.html
#	https://quarto.org/docs/projects/quarto-projects.html#shared-metadata
#	https://quarto.org/docs/websites/website-drafts.html

    
    
   


